name: generateHtml

on:
  push:
    branches: [ main ]
    paths:
    - 'scripts/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - run: npm install
    - run: npm run publishHtml
    
    - name: Commit files
    - run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Automated HTML generation for GitHub Pages"
    
    - name: GitHub Push
    - uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
    
